export const initialState = {
	play: false,
	getNumberPlay: false,
	colorPlay: false,
	shapePlay: false,
	getAlphabet: false,
	getNumbers: false,
	getColors: false,
	getShape: false,
	colorMain: false,
	shapeHome: false,
	items: [],
	getNumberCatOne: [],
	getNumberCatTwo: [],
	colors: [],
	buttons: [],
	shapes: [],
	compLetters: [],
	compare: false,
	speaking: false,
	winner: '',
	text: '',
	getColor: 'green',
	getBackgroundColor: 'black',
	getBgColor: 'white',
}
